services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: b2b
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      MYSQL_ROOT_PASSWORD: root
    ports: ["3306:3306"]
    volumes:
      - b2b-mysql:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 40

  db-migrate:
    image: mysql:8.0
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./db:/db
    command: >
      bash -lc "
        until mysql -h mysql -u root -proot -e 'select 1'; do sleep 2; done &&
        mysql -h mysql -u root -proot b2b < /db/schema.sql &&
        mysql -h mysql -u root -proot b2b < /db/seed.sql
      "

  customers-api:
    build: ./packages/customers-api
    #env_file: ./packages/customers-api/.env.example
    env_file: ./packages/customers-api/.env
    #!Solo sobreescribimos DB_HOST
    environment:
      DB_HOST: mysql
    depends_on:
      mysql:
        condition: service_healthy
      db-migrate:
        condition: service_completed_successfully
    ports: ["3001:3001"]

  orders-api:
    build: ./packages/orders-api
    #env_file: ./packages/orders-api/.env.example
    env_file: ./packages/orders-api/.env
    #!Solo sobreescribimos DB_HOST y CUSTOMERS_API_BASE 
    environment:
      DB_HOST: mysql
      CUSTOMERS_API_BASE: http://customers-api:3001
    depends_on:
      mysql:
        condition: service_healthy
      db-migrate:
        condition: service_completed_successfully
      customers-api:
        condition: service_started
    ports: ["3002:3002"]

volumes:
  b2b-mysql:
